// Generated by TSschema from ./const.json - do not edit, regenerate instead.
/* eslint-disable */
import type schema from "./const.json";
import type { TSSchemaFragment, TSSchemaType } from "../../src/index.js";

export type Schema = typeof schema;

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Const = Models["Const"];
