// Generated by TSschema from ./const.json - do not edit, regenerate instead.
/* eslint-disable */
declare const _0: "https://json-schema.org/draft/2020-12/schema";
declare const _1: "urn:tsschema:schema:const";
declare const _2: "const";
declare const _3: {
  readonly Const: {
    readonly const: 123;
  };
};
export { _0 as $schema, _1 as $id, _2 as title, _3 as $defs };
