// Generated by TSschema from ./enum.json - do not edit, regenerate instead.
/* eslint-disable */
declare const _0: "https://json-schema.org/draft/2020-12/schema";
declare const _1: "urn:tsschema:schema:enum";
declare const _2: "enum";
declare const _3: {
  readonly Enum: {
    readonly enum: readonly [
      "Aaa",
      "Bbb",
      "Ccc",
    ];
  };
};
export { _0 as $schema, _1 as $id, _2 as title, _3 as $defs };
