// Generated by TSschema from ./edge.json - do not edit, regenerate instead.
/* eslint-disable */
declare const _0: "https://json-schema.org/draft/2020-12/schema";
declare const _1: "urn:tsschema:schema:edge";
declare const _2: "edge";
declare const _3: {
  readonly "empty-array": readonly [];
  readonly "empty-object": {};
  readonly values: readonly [
    true,
    null,
    -1.5,
    "quote\"d",
  ];
};
declare const _4: {
  readonly Plain: {
    readonly type: "object";
    readonly properties: {
      readonly "kebab-property": {
        readonly type: "integer";
      };
      readonly items: {
        readonly type: "array";
        readonly prefixItems: readonly [
          {
            readonly type: "string";
          },
        ];
      };
    };
    readonly required: readonly [
      "kebab-property",
    ];
  };
  readonly "kebab-name": {
    readonly enum: readonly [
      "a",
      "b",
    ];
  };
  readonly string: {
    readonly type: "string";
  };
  readonly Schema: {
    readonly const: "colliding";
  };
  readonly Models: {
    readonly type: "boolean";
  };
};
export { _0 as $schema, _1 as $id, _2 as title, _3 as "x-vendor", _4 as $defs };
