// Generated by TSschema from ./enum.json - do not edit, regenerate instead.
/* eslint-disable */
import type schema from "./enum.json";
import type { TSSchemaFragment, TSSchemaType } from "../src/index.js";

export type Schema = typeof schema;

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Enum = Models["Enum"];
