// Generated by TSschema from ./schema.json - do not edit, regenerate instead.
/* eslint-disable */
import type schema from "./schema.json";
import type { TSSchemaFragment, TSSchemaType } from "../src/index.js";

export type Schema = typeof schema;

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type AssessmentKind = Models["AssessmentKind"];
export type ScalarRegister = Models["ScalarRegister"];
