// Generated by TSschema from ../assessment.json - do not edit, regenerate instead.
/* eslint-disable */
import type { TSSchemaFragment, TSSchemaType } from "../../src/index.js";

export type Schema = {
  readonly $schema: "https://json-schema.org/draft/2020-12/schema";
  readonly $id: "urn:cornerstone:schema:assessment";
  readonly title: "assessment";
  readonly $comment: "Definition bundle. Exported types: Assessment, AssessmentRecord. Reference one as #/$defs/<name>.";
  readonly $defs: {
    readonly Assessment: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly kind: {
          readonly $ref: "#/$defs/AssessmentKind";
        };
        readonly title: {
          readonly type: "string";
        };
        readonly weight: {
          readonly type: "number";
          readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
        };
        readonly maximumMarks: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 65535;
        };
        readonly dueAt: {
          readonly type: "string";
          readonly format: "date-time";
        };
        readonly isOpenBook: {
          readonly type: "boolean";
        };
        readonly class: {
          readonly anyOf: readonly [
            {
              readonly $ref: "#/$defs/Class";
            },
            {
              readonly type: "null";
            },
          ];
        };
        readonly record: {
          readonly $ref: "#/$defs/AssessmentRecord";
        };
      };
      readonly required: readonly [
        "id",
        "kind",
        "title",
        "weight",
        "maximumMarks",
        "dueAt",
        "isOpenBook",
        "record",
      ];
    };
    readonly AssessmentKind: {
      readonly type: "integer";
      readonly $comment: "Cornerstone.Fixtures.Schema.Enums.AssessmentKind (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "Quiz";
        },
        {
          readonly const: 1;
          readonly title: "MidtermExam";
        },
        {
          readonly const: 2;
          readonly title: "FinalExam";
        },
        {
          readonly const: 3;
          readonly title: "Essay";
        },
        {
          readonly const: 4;
          readonly title: "LabReport";
        },
        {
          readonly const: 5;
          readonly title: "Practical";
        },
        {
          readonly const: 6;
          readonly title: "OralDefence";
        },
        {
          readonly const: 7;
          readonly title: "GroupProject";
        },
      ];
    };
    readonly AssessmentRecord: {
      readonly type: "object";
      readonly properties: {
        readonly battery: {
          readonly $ref: "#/$defs/ScalarBattery";
        };
        readonly series: {
          readonly $ref: "#/$defs/ScalarSeries";
        };
        readonly register: {
          readonly $ref: "#/$defs/ScalarRegister";
        };
      };
      readonly required: readonly [
        "battery",
        "series",
        "register",
      ];
    };
    readonly Book: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly name: {
          readonly $ref: "#/$defs/BookName";
        };
        readonly isbn: {
          readonly type: "string";
        };
        readonly edition: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 255;
        };
        readonly pageCount: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 65535;
        };
        readonly price: {
          readonly type: "number";
          readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
        };
        readonly publishedOn: {
          readonly type: "string";
          readonly format: "date";
        };
        readonly hasDigitalLicence: {
          readonly type: "boolean";
        };
        readonly class: {
          readonly anyOf: readonly [
            {
              readonly $ref: "#/$defs/Class";
            },
            {
              readonly type: "null";
            },
          ];
        };
        readonly authors: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Person";
          };
        };
        readonly chapters: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Chapter";
          };
        };
      };
      readonly required: readonly [
        "id",
        "name",
        "isbn",
        "edition",
        "pageCount",
        "price",
        "publishedOn",
        "hasDigitalLicence",
        "authors",
        "chapters",
      ];
    };
    readonly BookName: {
      readonly type: "integer";
      readonly $comment: "Cornerstone.Fixtures.Schema.Enums.BookName (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "PrinciplesOfAlgebra";
        },
        {
          readonly const: 1;
          readonly title: "EuclideanFoundations";
        },
        {
          readonly const: 2;
          readonly title: "CalculusInMotion";
        },
        {
          readonly const: 3;
          readonly title: "StatisticsForTheCurious";
        },
        {
          readonly const: 4;
          readonly title: "TheLivingCell";
        },
        {
          readonly const: 5;
          readonly title: "ElementsAndReactions";
        },
        {
          readonly const: 6;
          readonly title: "MechanicsAndMotion";
        },
        {
          readonly const: 7;
          readonly title: "StructuredProgramming";
        },
        {
          readonly const: 8;
          readonly title: "IntroductionToRobotics";
        },
        {
          readonly const: 9;
          readonly title: "FieldGuideToTheNightSky";
        },
        {
          readonly const: 10;
          readonly title: "AtlasOfCivilizations";
        },
        {
          readonly const: 11;
          readonly title: "MapsAndMeridians";
        },
        {
          readonly const: 12;
          readonly title: "AnAnthologyOfVerse";
        },
        {
          readonly const: 13;
          readonly title: "TheWritersToolkit";
        },
        {
          readonly const: 14;
          readonly title: "LinguaLatinaPrimer";
        },
        {
          readonly const: 15;
          readonly title: "DialoguesOnReason";
        },
        {
          readonly const: 16;
          readonly title: "MarketsAndScarcity";
        },
        {
          readonly const: 17;
          readonly title: "HarmonyAndCounterpoint";
        },
        {
          readonly const: 18;
          readonly title: "ColourAndComposition";
        },
        {
          readonly const: 19;
          readonly title: "FoundationsOfKinesiology";
        },
      ];
    };
    readonly Chapter: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly ordinal: {
          readonly type: "integer";
          readonly minimum: -2147483648;
          readonly maximum: 2147483647;
        };
        readonly title: {
          readonly type: "string";
        };
        readonly startPage: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 65535;
        };
        readonly estimatedReadingTime: {
          readonly type: "string";
          readonly pattern: "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$";
          readonly $comment: "System.TimeSpan. System.Text.Json writes [-][d.]hh:mm:ss[.fffffff], not an ISO-8601 duration, so the \"duration\" format does not hold.";
        };
        readonly sections: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Section";
          };
        };
        readonly subChapters: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Chapter";
          };
        };
      };
      readonly required: readonly [
        "id",
        "ordinal",
        "title",
        "startPage",
        "estimatedReadingTime",
        "sections",
        "subChapters",
      ];
    };
    readonly Class: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly name: {
          readonly $ref: "#/$defs/ClassName";
        };
        readonly code: {
          readonly type: "string";
        };
        readonly term: {
          readonly $ref: "#/$defs/Term";
        };
        readonly academicYear: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 65535;
        };
        readonly credits: {
          readonly type: "number";
        };
        readonly seats: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 255;
        };
        readonly isEnrollmentOpen: {
          readonly type: "boolean";
        };
        readonly synopsis: {
          readonly type: "string";
        };
        readonly professor: {
          readonly anyOf: readonly [
            {
              readonly $ref: "#/$defs/Person";
            },
            {
              readonly type: "null";
            },
          ];
        };
        readonly students: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Person";
          };
        };
        readonly materials: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Book";
          };
        };
        readonly prerequisites: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Class";
          };
        };
        readonly schedule: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/ClassSession";
          };
        };
        readonly assessments: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Assessment";
          };
        };
        readonly room: {
          readonly anyOf: readonly [
            {
              readonly $ref: "#/$defs/Room";
            },
            {
              readonly type: "null";
            },
          ];
        };
      };
      readonly required: readonly [
        "id",
        "name",
        "code",
        "term",
        "academicYear",
        "credits",
        "seats",
        "isEnrollmentOpen",
        "synopsis",
        "students",
        "materials",
        "prerequisites",
        "schedule",
        "assessments",
      ];
    };
    readonly ClassName: {
      readonly type: "integer";
      readonly $comment: "Cornerstone.Fixtures.Schema.Enums.ClassName (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "Algebra";
        },
        {
          readonly const: 1;
          readonly title: "Geometry";
        },
        {
          readonly const: 2;
          readonly title: "Calculus";
        },
        {
          readonly const: 3;
          readonly title: "Statistics";
        },
        {
          readonly const: 4;
          readonly title: "Biology";
        },
        {
          readonly const: 5;
          readonly title: "Chemistry";
        },
        {
          readonly const: 6;
          readonly title: "Physics";
        },
        {
          readonly const: 7;
          readonly title: "ComputerScience";
        },
        {
          readonly const: 8;
          readonly title: "Robotics";
        },
        {
          readonly const: 9;
          readonly title: "Astronomy";
        },
        {
          readonly const: 10;
          readonly title: "WorldHistory";
        },
        {
          readonly const: 11;
          readonly title: "Geography";
        },
        {
          readonly const: 12;
          readonly title: "Literature";
        },
        {
          readonly const: 13;
          readonly title: "CreativeWriting";
        },
        {
          readonly const: 14;
          readonly title: "Latin";
        },
        {
          readonly const: 15;
          readonly title: "Philosophy";
        },
        {
          readonly const: 16;
          readonly title: "Economics";
        },
        {
          readonly const: 17;
          readonly title: "MusicTheory";
        },
        {
          readonly const: 18;
          readonly title: "VisualArts";
        },
        {
          readonly const: 19;
          readonly title: "PhysicalEducation";
        },
      ];
    };
    readonly ClassSession: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly day: {
          readonly $ref: "#/$defs/DayOfWeek";
        };
        readonly startsAt: {
          readonly type: "string";
          readonly pattern: "^([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(\\.\\d{1,7})?$";
          readonly $comment: "System.TimeOnly. System.Text.Json writes hh:mm:ss[.fffffff] with no UTC offset, so the JSON Schema \"time\" format (RFC 3339 full-time) does not hold.";
        };
        readonly duration: {
          readonly type: "string";
          readonly pattern: "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$";
          readonly $comment: "System.TimeSpan. System.Text.Json writes [-][d.]hh:mm:ss[.fffffff], not an ISO-8601 duration, so the \"duration\" format does not hold.";
        };
        readonly isRemote: {
          readonly type: "boolean";
        };
        readonly room: {
          readonly anyOf: readonly [
            {
              readonly $ref: "#/$defs/Room";
            },
            {
              readonly type: "null";
            },
          ];
        };
      };
      readonly required: readonly [
        "id",
        "day",
        "startsAt",
        "duration",
        "isRemote",
      ];
    };
    readonly DayOfWeek: {
      readonly type: "integer";
      readonly $comment: "System.DayOfWeek (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "Sunday";
        },
        {
          readonly const: 1;
          readonly title: "Monday";
        },
        {
          readonly const: 2;
          readonly title: "Tuesday";
        },
        {
          readonly const: 3;
          readonly title: "Wednesday";
        },
        {
          readonly const: 4;
          readonly title: "Thursday";
        },
        {
          readonly const: 5;
          readonly title: "Friday";
        },
        {
          readonly const: 6;
          readonly title: "Saturday";
        },
      ];
    };
    readonly Exercise: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly label: {
          readonly type: "string";
        };
        readonly prompt: {
          readonly type: "string";
        };
        readonly difficulty: {
          readonly type: "number";
        };
        readonly hasWorkedSolution: {
          readonly type: "boolean";
        };
        readonly marks: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 255;
        };
      };
      readonly required: readonly [
        "id",
        "label",
        "prompt",
        "difficulty",
        "hasWorkedSolution",
        "marks",
      ];
    };
    readonly Person: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly givenName: {
          readonly type: "string";
        };
        readonly familyName: {
          readonly type: "string";
        };
        readonly role: {
          readonly $ref: "#/$defs/PersonRole";
        };
        readonly bornOn: {
          readonly type: "string";
          readonly format: "date";
        };
        readonly email: {
          readonly type: "string";
        };
        readonly isActive: {
          readonly type: "boolean";
        };
        readonly gradePointAverage: {
          readonly type: "number";
        };
        readonly classes: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Class";
          };
        };
        readonly grades: {
          readonly type: "object";
          readonly $comment: "Keyed by Cornerstone.Fixtures.Schema.Enums.ClassName. System.Text.Json writes an enum dictionary key as the member name even under the default numeric converter, so this differs from the enum's value form.";
          readonly propertyNames: {
            readonly type: "string";
            readonly enum: readonly [
              "Algebra",
              "Geometry",
              "Calculus",
              "Statistics",
              "Biology",
              "Chemistry",
              "Physics",
              "ComputerScience",
              "Robotics",
              "Astronomy",
              "WorldHistory",
              "Geography",
              "Literature",
              "CreativeWriting",
              "Latin",
              "Philosophy",
              "Economics",
              "MusicTheory",
              "VisualArts",
              "PhysicalEducation",
            ];
          };
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: -2147483648;
            readonly maximum: 2147483647;
          };
        };
        readonly contactMethods: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
          };
        };
        readonly mentor: {
          readonly anyOf: readonly [
            {
              readonly $ref: "#/$defs/Person";
            },
            {
              readonly type: "null";
            },
          ];
        };
        readonly advisees: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Person";
          };
        };
        readonly office: {
          readonly anyOf: readonly [
            {
              readonly $ref: "#/$defs/Room";
            },
            {
              readonly type: "null";
            },
          ];
        };
      };
      readonly required: readonly [
        "id",
        "givenName",
        "familyName",
        "role",
        "bornOn",
        "email",
        "isActive",
        "gradePointAverage",
        "classes",
        "grades",
        "contactMethods",
        "advisees",
      ];
    };
    readonly PersonRole: {
      readonly type: "integer";
      readonly $comment: "Cornerstone.Fixtures.Schema.Enums.PersonRole (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "Student";
        },
        {
          readonly const: 1;
          readonly title: "Professor";
        },
        {
          readonly const: 2;
          readonly title: "TeachingAssistant";
        },
        {
          readonly const: 3;
          readonly title: "Librarian";
        },
        {
          readonly const: 4;
          readonly title: "Counsellor";
        },
        {
          readonly const: 5;
          readonly title: "Administrator";
        },
      ];
    };
    readonly Room: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly code: {
          readonly type: "string";
        };
        readonly kind: {
          readonly $ref: "#/$defs/RoomKind";
        };
        readonly seats: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 65535;
        };
        readonly floor: {
          readonly type: "integer";
          readonly minimum: -128;
          readonly maximum: 127;
        };
        readonly classes: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Class";
          };
        };
      };
      readonly required: readonly [
        "id",
        "code",
        "kind",
        "seats",
        "floor",
        "classes",
      ];
    };
    readonly RoomKind: {
      readonly type: "integer";
      readonly $comment: "Cornerstone.Fixtures.Schema.Enums.RoomKind (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "LectureHall";
        },
        {
          readonly const: 1;
          readonly title: "Classroom";
        },
        {
          readonly const: 2;
          readonly title: "Laboratory";
        },
        {
          readonly const: 3;
          readonly title: "SeminarRoom";
        },
        {
          readonly const: 4;
          readonly title: "Studio";
        },
        {
          readonly const: 5;
          readonly title: "Workshop";
        },
        {
          readonly const: 6;
          readonly title: "Gymnasium";
        },
        {
          readonly const: 7;
          readonly title: "ReadingRoom";
        },
        {
          readonly const: 8;
          readonly title: "Auditorium";
        },
      ];
    };
    readonly ScalarBattery: {
      readonly type: "object";
      readonly properties: {
        readonly isProctored: {
          readonly type: "boolean";
        };
        readonly curveAdjustment: {
          readonly type: "integer";
          readonly minimum: -128;
          readonly maximum: 127;
        };
        readonly rawScore: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 255;
        };
        readonly seatNumber: {
          readonly type: "integer";
          readonly minimum: -32768;
          readonly maximum: 32767;
        };
        readonly itemCount: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 65535;
        };
        readonly totalPoints: {
          readonly type: "integer";
          readonly minimum: -2147483648;
          readonly maximum: 2147483647;
        };
        readonly submissionSequence: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly maximum: 4294967295;
        };
        readonly elapsedTicks: {
          readonly type: "integer";
          readonly $comment: "System.Int64. Bounds are omitted: they are not exactly representable in IEEE-754, and values beyond 2^53 lose precision in readers that parse JSON numbers as doubles.";
        };
        readonly integrityChecksum: {
          readonly type: "integer";
          readonly minimum: 0;
          readonly $comment: "System.UInt64. The upper bound is omitted: it is not exactly representable in IEEE-754.";
        };
        readonly percentileRank: {
          readonly type: "number";
        };
        readonly scaledScore: {
          readonly type: "number";
        };
        readonly weightedAverage: {
          readonly type: "number";
          readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
        };
        readonly letterGrade: {
          readonly type: "string";
          readonly minLength: 1;
          readonly maxLength: 1;
        };
        readonly remarks: {
          readonly type: "string";
        };
        readonly responseId: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly administeredOn: {
          readonly type: "string";
          readonly format: "date";
        };
        readonly startedAt: {
          readonly type: "string";
          readonly pattern: "^([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(\\.\\d{1,7})?$";
          readonly $comment: "System.TimeOnly. System.Text.Json writes hh:mm:ss[.fffffff] with no UTC offset, so the JSON Schema \"time\" format (RFC 3339 full-time) does not hold.";
        };
        readonly allowedDuration: {
          readonly type: "string";
          readonly pattern: "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$";
          readonly $comment: "System.TimeSpan. System.Text.Json writes [-][d.]hh:mm:ss[.fffffff], not an ISO-8601 duration, so the \"duration\" format does not hold.";
        };
        readonly recordedAtUtc: {
          readonly type: "string";
          readonly format: "date-time";
          readonly $comment: "System.DateTime. The offset suffix is present only when DateTimeKind is Utc or Local; a DateTimeKind.Unspecified value is written without one and would not satisfy \"date-time\".";
        };
        readonly submittedAt: {
          readonly type: "string";
          readonly format: "date-time";
        };
      };
      readonly required: readonly [
        "isProctored",
        "curveAdjustment",
        "rawScore",
        "seatNumber",
        "itemCount",
        "totalPoints",
        "submissionSequence",
        "elapsedTicks",
        "integrityChecksum",
        "percentileRank",
        "scaledScore",
        "weightedAverage",
        "letterGrade",
        "remarks",
        "responseId",
        "administeredOn",
        "startedAt",
        "allowedDuration",
        "recordedAtUtc",
        "submittedAt",
      ];
    };
    readonly ScalarRegister: {
      readonly type: "object";
      readonly properties: {
        readonly answeredByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "boolean";
          };
        };
        readonly curveByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: -128;
            readonly maximum: 127;
          };
        };
        readonly rawScoreByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 255;
          };
        };
        readonly seatByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: -32768;
            readonly maximum: 32767;
          };
        };
        readonly attemptsByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 65535;
          };
        };
        readonly pointsByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: -2147483648;
            readonly maximum: 2147483647;
          };
        };
        readonly sequenceByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 4294967295;
          };
        };
        readonly elapsedTicksByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly $comment: "System.Int64. Bounds are omitted: they are not exactly representable in IEEE-754, and values beyond 2^53 lose precision in readers that parse JSON numbers as doubles.";
          };
        };
        readonly checksumByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly $comment: "System.UInt64. The upper bound is omitted: it is not exactly representable in IEEE-754.";
          };
        };
        readonly percentileByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "number";
          };
        };
        readonly scaledScoreByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "number";
          };
        };
        readonly weightByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "number";
            readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
          };
        };
        readonly letterGradeByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly minLength: 1;
            readonly maxLength: 1;
          };
        };
        readonly remarkByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
          };
        };
        readonly responseIdByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "uuid";
          };
        };
        readonly markedOnByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "date";
          };
        };
        readonly openedAtByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly pattern: "^([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(\\.\\d{1,7})?$";
            readonly $comment: "System.TimeOnly. System.Text.Json writes hh:mm:ss[.fffffff] with no UTC offset, so the JSON Schema \"time\" format (RFC 3339 full-time) does not hold.";
          };
        };
        readonly durationByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly pattern: "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$";
            readonly $comment: "System.TimeSpan. System.Text.Json writes [-][d.]hh:mm:ss[.fffffff], not an ISO-8601 duration, so the \"duration\" format does not hold.";
          };
        };
        readonly recordedAtUtcByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "date-time";
            readonly $comment: "System.DateTime. The offset suffix is present only when DateTimeKind is Utc or Local; a DateTimeKind.Unspecified value is written without one and would not satisfy \"date-time\".";
          };
        };
        readonly savedAtByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "date-time";
          };
        };
        readonly remarkByItemNumber: {
          readonly type: "object";
          readonly propertyNames: {
            readonly type: "string";
            readonly pattern: "^-?(0|[1-9]\\d*)$";
          };
          readonly additionalProperties: {
            readonly type: "string";
          };
        };
        readonly scoreByResponseId: {
          readonly type: "object";
          readonly propertyNames: {
            readonly type: "string";
            readonly format: "uuid";
          };
          readonly additionalProperties: {
            readonly type: "number";
          };
        };
        readonly weightByAssessmentKind: {
          readonly type: "object";
          readonly $comment: "Keyed by Cornerstone.Fixtures.Schema.Enums.AssessmentKind. System.Text.Json writes an enum dictionary key as the member name even under the default numeric converter, so this differs from the enum's value form.";
          readonly propertyNames: {
            readonly type: "string";
            readonly enum: readonly [
              "Quiz",
              "MidtermExam",
              "FinalExam",
              "Essay",
              "LabReport",
              "Practical",
              "OralDefence",
              "GroupProject",
            ];
          };
          readonly additionalProperties: {
            readonly type: "number";
            readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
          };
        };
        readonly attendanceByDate: {
          readonly type: "object";
          readonly propertyNames: {
            readonly type: "string";
            readonly format: "date";
          };
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 65535;
          };
        };
      };
      readonly required: readonly [
        "answeredByItem",
        "curveByItem",
        "rawScoreByItem",
        "seatByItem",
        "attemptsByItem",
        "pointsByItem",
        "sequenceByItem",
        "elapsedTicksByItem",
        "checksumByItem",
        "percentileByItem",
        "scaledScoreByItem",
        "weightByItem",
        "letterGradeByItem",
        "remarkByItem",
        "responseIdByItem",
        "markedOnByItem",
        "openedAtByItem",
        "durationByItem",
        "recordedAtUtcByItem",
        "savedAtByItem",
        "remarkByItemNumber",
        "scoreByResponseId",
        "weightByAssessmentKind",
        "attendanceByDate",
      ];
    };
    readonly ScalarSeries: {
      readonly type: "object";
      readonly properties: {
        readonly attemptedFlags: {
          readonly type: "array";
          readonly items: {
            readonly type: "boolean";
          };
        };
        readonly curveAdjustments: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: -128;
            readonly maximum: 127;
          };
        };
        readonly rawScores: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 255;
          };
        };
        readonly seatNumbers: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: -32768;
            readonly maximum: 32767;
          };
        };
        readonly attemptCounts: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 65535;
          };
        };
        readonly pointsPerItem: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: -2147483648;
            readonly maximum: 2147483647;
          };
        };
        readonly submissionSequences: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 4294967295;
          };
        };
        readonly elapsedTicksPerItem: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly $comment: "System.Int64. Bounds are omitted: they are not exactly representable in IEEE-754, and values beyond 2^53 lose precision in readers that parse JSON numbers as doubles.";
          };
        };
        readonly integrityChecksums: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly $comment: "System.UInt64. The upper bound is omitted: it is not exactly representable in IEEE-754.";
          };
        };
        readonly percentileRanks: {
          readonly type: "array";
          readonly items: {
            readonly type: "number";
          };
        };
        readonly scaledScores: {
          readonly type: "array";
          readonly items: {
            readonly type: "number";
          };
        };
        readonly weightedAverages: {
          readonly type: "array";
          readonly items: {
            readonly type: "number";
            readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
          };
        };
        readonly letterGrades: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
            readonly minLength: 1;
            readonly maxLength: 1;
          };
        };
        readonly remarks: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
          };
        };
        readonly responseIds: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
            readonly format: "uuid";
          };
        };
        readonly markedOn: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
            readonly format: "date";
          };
        };
        readonly openedAt: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
            readonly pattern: "^([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(\\.\\d{1,7})?$";
            readonly $comment: "System.TimeOnly. System.Text.Json writes hh:mm:ss[.fffffff] with no UTC offset, so the JSON Schema \"time\" format (RFC 3339 full-time) does not hold.";
          };
        };
        readonly durations: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
            readonly pattern: "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$";
            readonly $comment: "System.TimeSpan. System.Text.Json writes [-][d.]hh:mm:ss[.fffffff], not an ISO-8601 duration, so the \"duration\" format does not hold.";
          };
        };
        readonly recordedAtUtc: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
            readonly format: "date-time";
            readonly $comment: "System.DateTime. The offset suffix is present only when DateTimeKind is Utc or Local; a DateTimeKind.Unspecified value is written without one and would not satisfy \"date-time\".";
          };
        };
        readonly savedAt: {
          readonly type: "array";
          readonly items: {
            readonly type: "string";
            readonly format: "date-time";
          };
        };
        readonly answerSheetScan: {
          readonly type: "array";
          readonly items: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 255;
          };
        };
      };
      readonly required: readonly [
        "attemptedFlags",
        "curveAdjustments",
        "rawScores",
        "seatNumbers",
        "attemptCounts",
        "pointsPerItem",
        "submissionSequences",
        "elapsedTicksPerItem",
        "integrityChecksums",
        "percentileRanks",
        "scaledScores",
        "weightedAverages",
        "letterGrades",
        "remarks",
        "responseIds",
        "markedOn",
        "openedAt",
        "durations",
        "recordedAtUtc",
        "savedAt",
        "answerSheetScan",
      ];
    };
    readonly Section: {
      readonly type: "object";
      readonly properties: {
        readonly id: {
          readonly type: "string";
          readonly format: "uuid";
        };
        readonly number: {
          readonly type: "string";
        };
        readonly heading: {
          readonly type: "string";
        };
        readonly body: {
          readonly type: "string";
        };
        readonly wordCount: {
          readonly type: "integer";
          readonly minimum: -2147483648;
          readonly maximum: 2147483647;
        };
        readonly exercises: {
          readonly type: "array";
          readonly items: {
            readonly $ref: "#/$defs/Exercise";
          };
        };
      };
      readonly required: readonly [
        "id",
        "number",
        "heading",
        "body",
        "wordCount",
        "exercises",
      ];
    };
    readonly Term: {
      readonly type: "integer";
      readonly $comment: "Cornerstone.Fixtures.Schema.Enums.Term (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "Autumn";
        },
        {
          readonly const: 1;
          readonly title: "Winter";
        },
        {
          readonly const: 2;
          readonly title: "Spring";
        },
        {
          readonly const: 3;
          readonly title: "Summer";
        },
      ];
    };
  };
};

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Assessment = Models["Assessment"];
export type AssessmentKind = Models["AssessmentKind"];
export type AssessmentRecord = Models["AssessmentRecord"];
export type Book = Models["Book"];
export type BookName = Models["BookName"];
export type Chapter = Models["Chapter"];
export type Class = Models["Class"];
export type ClassName = Models["ClassName"];
export type ClassSession = Models["ClassSession"];
export type DayOfWeek = Models["DayOfWeek"];
export type Exercise = Models["Exercise"];
export type Person = Models["Person"];
export type PersonRole = Models["PersonRole"];
export type Room = Models["Room"];
export type RoomKind = Models["RoomKind"];
export type ScalarBattery = Models["ScalarBattery"];
export type ScalarRegister = Models["ScalarRegister"];
export type ScalarSeries = Models["ScalarSeries"];
export type Section = Models["Section"];
export type Term = Models["Term"];
