// Generated by TSschema from ../const.json - do not edit, regenerate instead.
/* eslint-disable */
import type { TSSchemaFragment, TSSchemaType } from "../../src/index.js";

export type Schema = {
  readonly $schema: "https://json-schema.org/draft/2020-12/schema";
  readonly $id: "urn:tsschema:schema:const";
  readonly title: "const";
  readonly $defs: {
    readonly Const: {
      readonly const: 123;
    };
  };
};

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Const = Models["Const"];
