// Generated by TSschema from ../edge.json - do not edit, regenerate instead.
/* eslint-disable */
import type { TSSchemaFragment, TSSchemaType } from "../../src/index.js";

export type Schema = {
  readonly $schema: "https://json-schema.org/draft/2020-12/schema";
  readonly $id: "urn:tsschema:schema:edge";
  readonly title: "edge";
  readonly "x-vendor": {
    readonly "empty-array": readonly [];
    readonly "empty-object": {};
    readonly values: readonly [
      true,
      null,
      -1.5,
      "quote\"d",
    ];
  };
  readonly $defs: {
    readonly Plain: {
      readonly type: "object";
      readonly properties: {
        readonly "kebab-property": {
          readonly type: "integer";
        };
        readonly items: {
          readonly type: "array";
          readonly prefixItems: readonly [
            {
              readonly type: "string";
            },
          ];
        };
      };
      readonly required: readonly [
        "kebab-property",
      ];
    };
    readonly "kebab-name": {
      readonly enum: readonly [
        "a",
        "b",
      ];
    };
    readonly string: {
      readonly type: "string";
    };
    readonly Schema: {
      readonly const: "colliding";
    };
    readonly Models: {
      readonly type: "boolean";
    };
  };
};

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Plain = Models["Plain"];
