// Generated by TSschema from ../enum.json - do not edit, regenerate instead.
/* eslint-disable */
import type { TSSchemaFragment, TSSchemaType } from "../../src/index.js";

export type Schema = {
  readonly $schema: "https://json-schema.org/draft/2020-12/schema";
  readonly $id: "urn:tsschema:schema:enum";
  readonly title: "enum";
  readonly $defs: {
    readonly Enum: {
      readonly enum: readonly [
        "Aaa",
        "Bbb",
        "Ccc",
      ];
    };
  };
};

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Enum = Models["Enum"];
