// Generated by TSschema from ../schema.json - do not edit, regenerate instead.
/* eslint-disable */
import type { TSSchemaFragment, TSSchemaType } from "../../src/index.js";

export type Schema = {
  readonly $schema: "https://json-schema.org/draft/2020-12/schema";
  readonly $id: "urn:cornerstone:schema:schema";
  readonly title: "schema";
  readonly $comment: "Definition bundle. Exported types: ScalarRegister. Reference one as #/$defs/<name>.";
  readonly $defs: {
    readonly AssessmentKind: {
      readonly type: "integer";
      readonly $comment: "Cornerstone.Fixtures.Schema.Enums.AssessmentKind (System.Int32). System.Text.Json writes the numeric value here; as a dictionary key the same type is written as the member name instead.";
      readonly oneOf: readonly [
        {
          readonly const: 0;
          readonly title: "Quiz";
        },
        {
          readonly const: 1;
          readonly title: "MidtermExam";
        },
        {
          readonly const: 2;
          readonly title: "FinalExam";
        },
        {
          readonly const: 3;
          readonly title: "Essay";
        },
        {
          readonly const: 4;
          readonly title: "LabReport";
        },
        {
          readonly const: 5;
          readonly title: "Practical";
        },
        {
          readonly const: 6;
          readonly title: "OralDefence";
        },
        {
          readonly const: 7;
          readonly title: "GroupProject";
        },
      ];
    };
    readonly ScalarRegister: {
      readonly type: "object";
      readonly properties: {
        readonly answeredByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "boolean";
          };
        };
        readonly curveByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: -128;
            readonly maximum: 127;
          };
        };
        readonly rawScoreByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 255;
          };
        };
        readonly seatByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: -32768;
            readonly maximum: 32767;
          };
        };
        readonly attemptsByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 65535;
          };
        };
        readonly pointsByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: -2147483648;
            readonly maximum: 2147483647;
          };
        };
        readonly sequenceByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 4294967295;
          };
        };
        readonly elapsedTicksByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly $comment: "System.Int64. Bounds are omitted: they are not exactly representable in IEEE-754, and values beyond 2^53 lose precision in readers that parse JSON numbers as doubles.";
          };
        };
        readonly checksumByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly $comment: "System.UInt64. The upper bound is omitted: it is not exactly representable in IEEE-754.";
          };
        };
        readonly percentileByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "number";
          };
        };
        readonly scaledScoreByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "number";
          };
        };
        readonly weightByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "number";
            readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
          };
        };
        readonly letterGradeByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly minLength: 1;
            readonly maxLength: 1;
          };
        };
        readonly remarkByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
          };
        };
        readonly responseIdByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "uuid";
          };
        };
        readonly markedOnByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "date";
          };
        };
        readonly openedAtByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly pattern: "^([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(\\.\\d{1,7})?$";
            readonly $comment: "System.TimeOnly. System.Text.Json writes hh:mm:ss[.fffffff] with no UTC offset, so the JSON Schema \"time\" format (RFC 3339 full-time) does not hold.";
          };
        };
        readonly durationByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly pattern: "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$";
            readonly $comment: "System.TimeSpan. System.Text.Json writes [-][d.]hh:mm:ss[.fffffff], not an ISO-8601 duration, so the \"duration\" format does not hold.";
          };
        };
        readonly recordedAtUtcByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "date-time";
            readonly $comment: "System.DateTime. The offset suffix is present only when DateTimeKind is Utc or Local; a DateTimeKind.Unspecified value is written without one and would not satisfy \"date-time\".";
          };
        };
        readonly savedAtByItem: {
          readonly type: "object";
          readonly additionalProperties: {
            readonly type: "string";
            readonly format: "date-time";
          };
        };
        readonly remarkByItemNumber: {
          readonly type: "object";
          readonly propertyNames: {
            readonly type: "string";
            readonly pattern: "^-?(0|[1-9]\\d*)$";
          };
          readonly additionalProperties: {
            readonly type: "string";
          };
        };
        readonly scoreByResponseId: {
          readonly type: "object";
          readonly propertyNames: {
            readonly type: "string";
            readonly format: "uuid";
          };
          readonly additionalProperties: {
            readonly type: "number";
          };
        };
        readonly weightByAssessmentKind: {
          readonly type: "object";
          readonly $comment: "Keyed by Cornerstone.Fixtures.Schema.Enums.AssessmentKind. System.Text.Json writes an enum dictionary key as the member name even under the default numeric converter, so this differs from the enum's value form.";
          readonly propertyNames: {
            readonly type: "string";
            readonly enum: readonly [
              "Quiz",
              "MidtermExam",
              "FinalExam",
              "Essay",
              "LabReport",
              "Practical",
              "OralDefence",
              "GroupProject",
            ];
          };
          readonly additionalProperties: {
            readonly type: "number";
            readonly $comment: "System.Decimal. Written as an unquoted JSON number with its scale preserved; a reader backed by an IEEE-754 double cannot hold it exactly.";
          };
        };
        readonly attendanceByDate: {
          readonly type: "object";
          readonly propertyNames: {
            readonly type: "string";
            readonly format: "date";
          };
          readonly additionalProperties: {
            readonly type: "integer";
            readonly minimum: 0;
            readonly maximum: 65535;
          };
        };
      };
      readonly required: readonly [
        "answeredByItem",
        "curveByItem",
        "rawScoreByItem",
        "seatByItem",
        "attemptsByItem",
        "pointsByItem",
        "sequenceByItem",
        "elapsedTicksByItem",
        "checksumByItem",
        "percentileByItem",
        "scaledScoreByItem",
        "weightByItem",
        "letterGradeByItem",
        "remarkByItem",
        "responseIdByItem",
        "markedOnByItem",
        "openedAtByItem",
        "durationByItem",
        "recordedAtUtcByItem",
        "savedAtByItem",
        "remarkByItemNumber",
        "scoreByResponseId",
        "weightByAssessmentKind",
        "attendanceByDate",
      ];
    };
  };
};

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type AssessmentKind = Models["AssessmentKind"];
export type ScalarRegister = Models["ScalarRegister"];
