// Generated by TSschema from ../const.json - do not edit, regenerate instead.
/* eslint-disable */
import type { TSSchemaJSONCollection, TSSchemaFragment, TSSchemaType } from "../../src/index.js";

const schema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:tsschema:schema:const",
  "title": "const",
  "$defs": {
    "Const": {
      "const": 123
    }
  }
} as const;
export default schema satisfies TSSchemaJSONCollection;

export type Schema = typeof schema;

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Const = Models["Const"];
