// Generated by TSschema from ../enum.json - do not edit, regenerate instead.
/* eslint-disable */
import type { TSSchemaJSONCollection, TSSchemaFragment, TSSchemaType } from "../../src/index.js";

const schema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:tsschema:schema:enum",
  "title": "enum",
  "$defs": {
    "Enum": {
      "enum": [
        "Aaa",
        "Bbb",
        "Ccc"
      ]
    }
  }
} as const;
export default schema satisfies TSSchemaJSONCollection;

export type Schema = typeof schema;

export type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };
export type Enum = Models["Enum"];
