/**
 * Code generation of TypeScript files from JSON schema files, so that a schema kept as a `.json` file keeps its literal types and can be used with the
 * type inference utilities, without being hand-copied into a `.ts` file declared `as const`.
 *
 * Supports three output modes:
 * - `sidecar` generates a `<name>.d.json.ts` declaration file next to `<name>.json`, which TypeScript (with `allowArbitraryExtensions`) uses as the type
 *   of the JSON module itself, so the schema is still imported from `./<name>.json`,
 * - `module` generates a `<name>.schema.ts` module exporting the schema as an `as const` value, checked against the JSON schema type with `satisfies`,
 * - `types` generates a `<name>.schema.ts` module exporting only the schema's type, with no runtime value.
 *
 * Any mode can additionally generate a `Models` map type and a named type alias per fragment of a collection (in a separate `<name>.models.ts` file for
 * `sidecar`, as named imports from a JSON module are not allowed under `module: nodenext`).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative } from 'node:path';

// #region Options and results

/**
 * Represents a code generation output mode: a `.d.json.ts` declaration file next to the JSON file (`sidecar`), an `as const` schema module (`module`),
 * or a schema type only module (`types`)
 */
export type TSSchemaCodegenMode = 'sidecar' | 'module' | 'types';

/**
 * Represents code generation options. Unspecified options default to the `sidecar` mode, no model types and importing from `@ofzza/tsschema`.
 */
export type TSSchemaCodegenOptions = {
  /**
   * Output mode (defaults to `sidecar`)
   */
  mode?: TSSchemaCodegenMode;
  /**
   * If a `Models` map type and a named type alias per fragment of a collection should also be generated (defaults to `false`)
   */
  models?: boolean;
  /**
   * Directory to generate `module` / `types` mode files into, instead of next to their JSON files (not supported by the `sidecar` mode, whose
   * declaration files must sit next to their JSON files)
   */
  outDir?: string;
  /**
   * Module specifier generated code imports the TSschema types from (defaults to `@ofzza/tsschema`)
   */
  importFrom?: string;
};

/**
 * Represents a generated file
 */
export type TSSchemaCodegenFile = {
  /**
   * Path of the generated file
   */
  path: string;
  /**
   * Content of the generated file
   */
  content: string;
};

/**
 * Represents the outcome for a single generated file: `written` (created or updated), `unchanged` (already up to date) or `stale` (out of date, or
 * missing, when only checking)
 */
export type TSSchemaCodegenFileStatus = 'written' | 'unchanged' | 'stale';

/**
 * Represents the result of generating code from one or more JSON schema files
 */
export type TSSchemaCodegenResult = {
  /**
   * Path and outcome of every file generated
   */
  files: { path: string; source: string; status: TSSchemaCodegenFileStatus }[];
};

// #endregion

// #region Rendering

/**
 * First line of every generated file, used to recognize a generated file before overwriting it
 */
const _HEADER = '// Generated by TSschema';

/**
 * Words which can not be used as a type alias name
 */
const _RESERVED_NAMES = new Set([
  ...['break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do', 'else', 'enum', 'export', 'extends', 'false'],
  ...['finally', 'for', 'function', 'if', 'import', 'in', 'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this', 'throw', 'true', 'try'],
  ...['typeof', 'var', 'void', 'while', 'with', 'implements', 'interface', 'let', 'package', 'private', 'protected', 'public', 'static', 'yield'],
  ...['any', 'bigint', 'boolean', 'never', 'number', 'object', 'string', 'symbol', 'undefined', 'unknown'],
]);

/**
 * Names declared by generated code itself, which a fragment's type alias must not shadow
 */
const _DECLARED_NAMES = new Set(['Schema', 'Models', 'Model', 'TSSchemaFragment', 'TSSchemaType', 'TSSchemaJSONSchema', 'TSSchemaJSONCollection']);

/**
 * Checks if a string is a valid identifier
 *
 * @param name String to check
 * @returns If the string is a valid identifier
 */
function _isIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

/**
 * Renders a property key, quoting it unless it is a valid identifier
 *
 * @param key Property key to render
 * @returns Rendered property key
 */
function _renderKey(key: string): string {
  return _isIdentifier(key) ? key : JSON.stringify(key);
}

/**
 * Renders the literal, read-only type of a JSON value, equivalent to the type the same value would have when declared `as const`
 *
 * @param value JSON value to render the type of
 * @param indent Indentation of the line the type starts on
 * @returns Rendered type
 */
function _renderType(value: unknown, indent: string = ''): string {
  const nested = `${indent}  `;
  // Primitive value: literal type
  if (value === null || typeof value !== 'object') {
    return JSON.stringify(value);
  }
  // Array: read-only tuple type
  if (Array.isArray(value)) {
    return !value.length ? 'readonly []' : `readonly [\n${value.map((item) => `${nested}${_renderType(item, nested)},`).join('\n')}\n${indent}]`;
  }
  // Object: read-only object type
  const entries = Object.entries(value);
  return !entries.length
    ? '{}'
    : `{\n${entries.map(([key, item]) => `${nested}readonly ${_renderKey(key)}: ${_renderType(item, nested)};`).join('\n')}\n${indent}}`;
}

/**
 * Checks if a JSON value is a JSON schema collection (an object with a `$defs` object)
 *
 * @param json JSON value to check
 * @returns If the value is a JSON schema collection
 */
function _isCollection(json: unknown): json is { $defs: Record<string, unknown> } {
  return _isObject(json) && _isObject(json.$defs);
}

/**
 * Checks if a JSON value is an object (and not an array)
 *
 * @param json JSON value to check
 * @returns If the value is an object
 */
function _isObject(json: unknown): json is Record<string, unknown> {
  return json !== null && typeof json === 'object' && !Array.isArray(json);
}

/**
 * Renders the header of a generated file, naming the JSON file it was generated from
 *
 * @param sourcePath Path of the JSON file
 * @param outputPath Path of the generated file
 * @returns Rendered header
 */
function _renderHeader(sourcePath: string, outputPath: string): string {
  return `${_HEADER} from ${_relativeSpecifier(outputPath, sourcePath)} - do not edit, regenerate instead.\n/* eslint-disable */\n`;
}

/**
 * Gets a relative module specifier (always starting with `./` or `../`, with `/` separators) from a file to another file
 *
 * @param fromPath Path of the importing file
 * @param toPath Path of the imported file
 * @returns Relative module specifier
 */
function _relativeSpecifier(fromPath: string, toPath: string): string {
  const specifier = relative(dirname(fromPath), toPath).split('\\').join('/');
  return specifier.startsWith('.') ? specifier : `./${specifier}`;
}

/**
 * Renders the model types of a schema: for a collection a `Models` map type and a named type alias per fragment (where the fragment's name is usable as
 * one), for any other schema object a single `Model` type, and nothing for a boolean schema
 *
 * @param json Parsed JSON schema
 * @returns Rendered model types
 */
function _renderModels(json: unknown): string {
  // Boolean schema: no models
  if (!_isObject(json)) {
    return '';
  }
  // Not a collection: a single model
  if (!_isCollection(json)) {
    return `\nexport type Model = TSSchemaType<Schema>;\n`;
  }
  // Collection: a map of all models, and an alias per model
  const aliases = Object.keys(json.$defs)
    .filter((name) => _isIdentifier(name) && !_RESERVED_NAMES.has(name) && !_DECLARED_NAMES.has(name))
    .map((name) => `export type ${name} = Models[${JSON.stringify(name)}];\n`)
    .join('');
  return `\nexport type Models = { [K in keyof Schema['$defs'] & string]: TSSchemaType<TSSchemaFragment<Schema, K>> };\n${aliases}`;
}

/**
 * Generates the files for a single JSON schema, without touching the file system
 *
 * @param sourcePath Path of the JSON schema file
 * @param json Parsed JSON schema
 * @param options Code generation options
 * @returns Generated files
 */
export function generateFiles(sourcePath: string, json: unknown, options: TSSchemaCodegenOptions = {}): TSSchemaCodegenFile[] {
  const { mode = 'sidecar', models = false, outDir, importFrom = '@ofzza/tsschema' } = options;
  const stem = basename(sourcePath).replace(/\.json$/i, '');
  const importTypes = (names: string[]) => `import type { ${names.join(', ')} } from ${JSON.stringify(importFrom)};\n`;
  const modelTypeImports = !models || !_isObject(json) ? [] : _isCollection(json) ? ['TSSchemaFragment', 'TSSchemaType'] : ['TSSchemaType'];

  // Sidecar: a declaration file of the JSON module, declaring each top-level key as a named export
  if (mode === 'sidecar') {
    if (outDir !== undefined) {
      throw new Error(`The 'sidecar' mode does not support an output directory: declaration files must sit next to their JSON files (${sourcePath})`);
    }
    if (!_isObject(json)) {
      throw new Error(`The 'sidecar' mode requires a JSON object at the top level of the schema; use the 'module' or 'types' mode instead (${sourcePath})`);
    }
    const sidecarPath = join(dirname(sourcePath), `${stem}.d.json.ts`);
    const entries = Object.entries(json);
    const declarations = entries.map(([, value], i) => `declare const _${i}: ${_renderType(value)};\n`).join('');
    const exported = entries.map(([key], i) => `_${i} as ${_isIdentifier(key) ? key : JSON.stringify(key)}`).join(', ');
    const files = [{ path: sidecarPath, content: `${_renderHeader(sourcePath, sidecarPath)}${declarations}export { ${exported} };\n` }];
    if (models) {
      const modelsPath = join(dirname(sourcePath), `${stem}.models.ts`);
      const content =
        `${_renderHeader(sourcePath, modelsPath)}import type schema from ${JSON.stringify(_relativeSpecifier(modelsPath, sourcePath))};\n` +
        `${importTypes(modelTypeImports)}\nexport type Schema = typeof schema;\n${_renderModels(json)}`;
      files.push({ path: modelsPath, content });
    }
    return files;
  }

  // Module or types: a single `.schema.ts` module
  const outputPath = join(outDir ?? dirname(sourcePath), `${stem}.schema.ts`);
  let body: string;
  if (mode === 'module') {
    const schemaType = _isCollection(json) ? 'TSSchemaJSONCollection' : 'TSSchemaJSONSchema';
    body =
      `${importTypes([schemaType, ...modelTypeImports])}\n` +
      `const schema = ${JSON.stringify(json, null, 2)} as const;\n` +
      // Checked as an identifier rather than as a literal, so unknown keywords (newer drafts, vendor extensions) are not rejected as excess properties
      `export default schema satisfies ${schemaType};\n\nexport type Schema = typeof schema;\n`;
  } else if (mode === 'types') {
    body = `${modelTypeImports.length ? `${importTypes(modelTypeImports)}\n` : ''}export type Schema = ${_renderType(json)};\n`;
  } else {
    throw new Error(`Unknown code generation mode '${String(mode)}'`);
  }
  return [{ path: outputPath, content: `${_renderHeader(sourcePath, outputPath)}${body}${models ? _renderModels(json) : ''}` }];
}

// #endregion

// #region File system

/**
 * Generates the files for one or more JSON schema files and writes them, skipping files that are already up to date. When only checking, nothing is
 * written, and every file that would have been written is reported as `stale` instead.
 *
 * Refuses to overwrite an existing file which was not generated by TSschema.
 *
 * @param sourcePaths Paths of the JSON schema files
 * @param options Code generation options, and if files should only be checked for being up to date
 * @returns Path and outcome of every generated file
 */
export function generate(sourcePaths: string[], options: TSSchemaCodegenOptions & { check?: boolean } = {}): TSSchemaCodegenResult {
  const { check = false, ...codegenOptions } = options;
  const result: TSSchemaCodegenResult = { files: [] };
  for (const sourcePath of sourcePaths) {
    const json: unknown = JSON.parse(readFileSync(sourcePath, 'utf8'));
    for (const file of generateFiles(sourcePath, json, codegenOptions)) {
      const existing = existsSync(file.path) ? readFileSync(file.path, 'utf8') : undefined;
      if (existing !== undefined && !existing.startsWith(_HEADER)) {
        throw new Error(`Refusing to overwrite ${file.path}, which was not generated by TSschema`);
      }
      const status: TSSchemaCodegenFileStatus = existing === file.content ? 'unchanged' : check ? 'stale' : 'written';
      if (status === 'written') {
        mkdirSync(dirname(file.path), { recursive: true });
        writeFileSync(file.path, file.content);
      }
      result.files.push({ path: file.path, source: sourcePath, status });
    }
  }
  return result;
}

// #endregion
